name: Setup BuildCharts 
description: Pulls and prepares BuildCharts Docker image
branding:
  icon: 'pie-chart'
  color: 'yellow'
runs:
  using: composite
  steps:
    - name: Pull buildcharts image
      shell: bash
      run: |
        docker pull buildcharts/buildcharts:latest