name: Setup BuildCharts
description: Runs `buildcharts generate` using Docker
branding:
  icon: 'pie-chart'
  color: 'yellow'
inputs:
  image:
    description: Docker image to use
    default: buildcharts/buildcharts:latest
runs:
  using: composite
  steps:
    - name: Run buildcharts generate
      shell: bash
      run: |
        set -euo pipefail

        echo "🚀 Running buildcharts generate from image: ${{ inputs.image }}"

        docker run --rm \
          -v "${GITHUB_WORKSPACE}:/app" \
          -w /app \
          ${{ inputs.image }} generate
